# Generated by Django 3.0.5 on 2020-12-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_exps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_exp',
            name='summary',
            field=models.CharField(max_length=400),
        ),
    ]
