# Generated by Django 3.0.5 on 2020-12-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_exps', '0002_auto_20201204_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_exp',
            name='title',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
