# Generated by Django 3.0.5 on 2020-12-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_exps', '0003_prof_exp_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default=False, max_length=100)),
                ('summary', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default=False, max_length=100)),
                ('summary', models.CharField(max_length=400)),
            ],
        ),
    ]
