# Generated by Django 3.0.5 on 2021-01-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_exps', '0005_auto_20201209_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curb_Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=False, max_length=100)),
                ('videofile', models.FileField(upload_to='', verbose_name=models.URLField(verbose_name='curbalertdemo.mp4'))),
            ],
        ),
    ]
